name: depgraph release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # build with gopack
      - name: build and package binaries
        uses: henryhale/gopack@v1.0.3
        with:
          name: depgraph
          path: "."
          dest: ./dist/
          ldflags: "-s -w -X 'main.version=$(git describe --tags)'"
          checksum: checksums.txt
          includeVersion: false

      - name: list binaries
        run: ls ./dist/

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
